# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name find_dropouts
NULL

find_dropouts <- function(df) {
    .Call('_dropout_find_dropouts', PACKAGE = 'dropout', df)
}

#' @name find_na_sequences
NULL

find_na_sequences <- function(sec_data, section_min) {
    .Call('_dropout_find_na_sequences', PACKAGE = 'dropout', sec_data, section_min)
}

